-- Staff fine-grained RBAC: preset roles + permission grant/deny overrides.

ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FULFILLMENT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'BILLING';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CATALOG';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FINANCE_VIEWER';

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "permissionsGrant" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "permissionsDeny" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
