/**
 * Build Vital Health white-label artwork from the PeptSci face + client logo.
 *
 * - Recolors PeptSci indigo (#2f2f80) → Vital Health navy (#2a5fa1)
 * - Replaces the left-rail molecule with the supplied logo, rotated −90° (bottom-to-top, like PeptSci)
 * - Rasterizes OL4891LP template PNG and a packing-slip wordmark PNG
 *
 * Run: npx tsx scripts/build-vital-health-template.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { Resvg } from '@resvg/resvg-js'

const ROOT = process.cwd()
const DIR = path.join(ROOT, 'public/labels/clients/vital-health')
const PEPTSCI = path.join(ROOT, 'public/labels/PEPTSCI LABEL SAMPLE.svg')
const LOGO = path.join(DIR, 'vital-health-logo.svg')
const EMPTY_OUT = path.join(DIR, 'vital-health-label-empty.svg')
const PNG_OUT = path.join(DIR, 'vital-health-label-template.png')
const BRAND_DIR = path.join(ROOT, 'public/brand')
const BRAND_PNG = path.join(BRAND_DIR, 'vital-health-logo-dark.png')

const NAVY = '#2a5fa1'
const MOLECULE_START = '<path class="st1" d="M19.01,43.76'
const BUD_START = 'M32.28,6.14'

function nestedLogo(logoSvg: string): string {
  const inner = logoSvg
    .replace(/<\?xml[^>]*>/, '')
    .replace(/<svg\b[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replaceAll('.st0', '.vh0')
    .replaceAll('.st1', '.vh1')
    .replaceAll('.st2', '.vh2')
    .replaceAll('.st3', '.vh3')
    .replaceAll('class="st0"', 'class="vh0"')
    .replaceAll('class="st1"', 'class="vh1"')
    .replaceAll('class="st2"', 'class="vh2"')
    .replaceAll('class="st3"', 'class="vh3"')
    .trim()

  // Landscape mark → vertical left rail, same bottom-to-top read as PeptSci / BATCH / RUO.
  // Native 392.97×236.53; after rotate(-90) the bbox is 236.53×392.97. Divider is at x=25.07.
  const logoW = 392.97
  const logoH = 236.53
  const railX = 1.1
  const railY = 2.2
  const railW = 22.9
  const railH = 49.6
  const scale = Math.min(railW / logoH, railH / logoW)
  const cx = railX + railW / 2
  const cy = railY + railH / 2
  const transform = `translate(${cx.toFixed(2)} ${cy.toFixed(2)}) scale(${scale.toFixed(5)}) rotate(-90) translate(${(-logoW / 2).toFixed(3)} ${(-logoH / 2).toFixed(3)})`

  return [
    `  <g id="vital-health-logo" transform="${transform}">`,
    inner
      .split('\n')
      .map((line) => (line.length ? `    ${line}` : line))
      .join('\n'),
    '  </g>',
    '',
  ].join('\n')
}

function assembleLabel(peptsci: string, logoSvg: string): string {
  const recolored = peptsci.replaceAll('#2f2f80', NAVY)
  const mol = recolored.indexOf(MOLECULE_START)
  const budPath = recolored.indexOf(BUD_START)
  if (mol < 0 || budPath < 0) {
    throw new Error('Could not locate PeptSci molecule / BUD paths to splice the logo.')
  }
  const budGroup = recolored.lastIndexOf('<g>', budPath)
  if (budGroup < mol) {
    throw new Error('BUD group start is before the molecule; splice aborted.')
  }
  return `${recolored.slice(0, mol)}${nestedLogo(logoSvg)}${recolored.slice(budGroup)}`
}

function main() {
  mkdirSync(DIR, { recursive: true })
  mkdirSync(BRAND_DIR, { recursive: true })

  const peptsci = readFileSync(PEPTSCI, 'utf8')
  const logoSvg = readFileSync(LOGO, 'utf8')
  const labelSvg = assembleLabel(peptsci, logoSvg)
  writeFileSync(EMPTY_OUT, labelSvg)
  console.log(`wrote ${EMPTY_OUT} (${labelSvg.length} bytes)`)

  const labelPng = new Resvg(labelSvg, {
    fitTo: { mode: 'width', value: 2880 },
    background: 'rgba(0,0,0,0)',
  })
    .render()
    .asPng()
  writeFileSync(PNG_OUT, labelPng)
  console.log(`wrote ${PNG_OUT} (${labelPng.length} bytes)`)

  const brandPng = new Resvg(logoSvg, {
    fitTo: { mode: 'width', value: 1200 },
    background: 'rgba(0,0,0,0)',
  })
    .render()
    .asPng()
  writeFileSync(BRAND_PNG, brandPng)
  console.log(`wrote ${BRAND_PNG} (${brandPng.length} bytes)`)

  const embedOut = path.join(ROOT, 'lib/labels/vitalHealthEmbeddedAssets.ts')
  writeFileSync(
    embedOut,
    [
      '// AUTO-GENERATED by scripts/build-vital-health-template.ts — do not edit by hand.',
      '// Base64 Vital Health label template PNG for Vercel (public/ is not in serverless bundles).',
      '',
      `export const VITAL_HEALTH_TEMPLATE_PNG_B64 = '${Buffer.from(labelPng).toString('base64')}'`,
      '',
    ].join('\n')
  )
  console.log(`wrote ${embedOut}`)
}

main()
