#!/usr/bin/env python3
"""Generate lib/labels/embeddedAssets.ts (base64 template PNG + ASCII-subset
brand fonts) so the label engine works with zero filesystem/tracing dependency
on serverless (Vercel). Run with the fonttools venv:

    /tmp/ftenv/bin/python scripts/build-label-assets.py

Fonts are subset to printable ASCII (U+0020..U+007E) to keep the bundle small;
pdf-lib subsets again at embed time.
"""
import base64
import io
import os

from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LABELS = os.path.join(ROOT, "public", "labels")
FONTS = os.path.join(ROOT, "public", "fonts", "labels")
OUT = os.path.join(ROOT, "lib", "labels", "embeddedAssets.ts")


def subset_font_b64(path: str) -> str:
    font = TTFont(path)
    opt = Options()
    opt.layout_features = ["*"]
    opt.name_IDs = ["*"]
    opt.recalc_bounds = True
    opt.drop_tables = []
    ss = Subsetter(options=opt)
    ss.populate(unicodes=range(0x20, 0x7F))
    ss.subset(font)
    buf = io.BytesIO()
    font.save(buf)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def file_b64(path: str) -> str:
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")


def main() -> None:
    template = file_b64(os.path.join(LABELS, "peptsci-label-template.png"))
    at_cond = subset_font_b64(os.path.join(FONTS, "AmericanTypewriter-Condensed.ttf"))
    sofia = subset_font_b64(os.path.join(FONTS, "SofiaPro-Regular.ttf"))

    parts = [
        "// AUTO-GENERATED by scripts/build-label-assets.py — do not edit by hand.",
        "// Base64 label artwork template + ASCII-subset brand fonts, embedded so the",
        "// label engine runs with no filesystem/tracing dependency (works on Vercel).",
        "",
        f"export const TEMPLATE_PNG_B64 = '{template}'",
        "",
        f"export const AMERICAN_TYPEWRITER_CONDENSED_B64 = '{at_cond}'",
        "",
        f"export const SOFIA_PRO_REGULAR_B64 = '{sofia}'",
        "",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(parts))

    kb = lambda s: round(len(s) * 3 / 4 / 1024, 1)
    print(f"wrote {OUT}")
    print(f"  template png : {kb(template)} KB")
    print(f"  AT condensed : {kb(at_cond)} KB (subset)")
    print(f"  Sofia Pro    : {kb(sofia)} KB (subset)")


if __name__ == "__main__":
    main()
