/**
 * Build Element Labs USA white-label artwork from the PeptSci face + client logo.
 *
 * - Recolors PeptSci indigo (#2f2f80) → Element Labs navy (#073162)
 * - Replaces the left-rail molecule with the supplied logo, rotated −90° (bottom-to-top, like PeptSci)
 * - Rasterizes OL4891LP template PNG and copies a packing-slip logo PNG
 *
 * The client supplied a transparent single-colour PNG (153×150) rather than a
 * vector mark, so the logo is embedded as a raster <image> inside the label SVG.
 * Drop a higher-resolution / SVG export at the same path to sharpen output and re-run.
 *
 * Run: npx tsx scripts/build-element-labs-template.ts
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs'
import path from 'node:path'
import { Resvg } from '@resvg/resvg-js'

const ROOT = process.cwd()
const DIR = path.join(ROOT, 'public/labels/clients/element-labs')
const PEPTSCI = path.join(ROOT, 'public/labels/PEPTSCI LABEL SAMPLE.svg')
const LOGO = path.join(DIR, 'element-labs-logo.png')
const EMPTY_OUT = path.join(DIR, 'element-labs-label-empty.svg')
const PNG_OUT = path.join(DIR, 'element-labs-label-template.png')
const BRAND_DIR = path.join(ROOT, 'public/brand')
const BRAND_PNG = path.join(BRAND_DIR, 'element-labs-logo-dark.png')

const NAVY = '#073162'
const MOLECULE_START = '<path class="st1" d="M19.01,43.76'
const BUD_START = 'M32.28,6.14'

/** Read PNG IHDR for intrinsic pixel size. */
function pngSize(buf: Buffer): { width: number; height: number } {
  if (buf.subarray(0, 8).toString('hex') !== '89504e470d0a1a0a') {
    throw new Error('Logo is not a PNG file.')
  }
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) }
}

function nestedLogo(logoPng: Buffer): string {
  const { width: logoW, height: logoH } = pngSize(logoPng)

  // Square mark → vertical left rail, same bottom-to-top read as PeptSci / BATCH / RUO.
  // After rotate(-90) the bbox is logoH×logoW. Divider is at x=25.07.
  const railX = 1.1
  const railY = 2.2
  const railW = 22.9
  const railH = 49.6
  const scale = Math.min(railW / logoH, railH / logoW)
  const cx = railX + railW / 2
  const cy = railY + railH / 2
  const transform = `translate(${cx.toFixed(2)} ${cy.toFixed(2)}) scale(${scale.toFixed(5)}) rotate(-90) translate(${(-logoW / 2).toFixed(3)} ${(-logoH / 2).toFixed(3)})`
  const href = `data:image/png;base64,${logoPng.toString('base64')}`

  return [
    `  <g id="element-labs-logo" transform="${transform}">`,
    `    <image width="${logoW}" height="${logoH}" href="${href}" xlink:href="${href}"/>`,
    '  </g>',
    '',
  ].join('\n')
}

function assembleLabel(peptsci: string, logoPng: Buffer): string {
  const recolored = peptsci
    .replaceAll('#2f2f80', NAVY)
    // Ensure the xlink namespace exists for the embedded <image>.
    .replace(
      /<svg\b(?![^>]*xmlns:xlink)([^>]*)>/,
      '<svg xmlns:xlink="http://www.w3.org/1999/xlink"$1>'
    )
  const mol = recolored.indexOf(MOLECULE_START)
  const budPath = recolored.indexOf(BUD_START)
  if (mol < 0 || budPath < 0) {
    throw new Error('Could not locate PeptSci molecule / BUD paths to splice the logo.')
  }
  const budGroup = recolored.lastIndexOf('<g>', budPath)
  if (budGroup < mol) {
    throw new Error('BUD group start is before the molecule; splice aborted.')
  }
  return `${recolored.slice(0, mol)}${nestedLogo(logoPng)}${recolored.slice(budGroup)}`
}

function main() {
  mkdirSync(DIR, { recursive: true })
  mkdirSync(BRAND_DIR, { recursive: true })

  const peptsci = readFileSync(PEPTSCI, 'utf8')
  const logoPng = readFileSync(LOGO)
  const labelSvg = assembleLabel(peptsci, logoPng)
  writeFileSync(EMPTY_OUT, labelSvg)
  console.log(`wrote ${EMPTY_OUT} (${labelSvg.length} bytes)`)

  const labelPng = new Resvg(labelSvg, {
    fitTo: { mode: 'width', value: 2880 },
    background: 'rgba(0,0,0,0)',
  })
    .render()
    .asPng()
  writeFileSync(PNG_OUT, labelPng)
  console.log(`wrote ${PNG_OUT} (${labelPng.length} bytes)`)

  // Packing-slip / vector-fallback logo: the source PNG is already transparent + dark.
  copyFileSync(LOGO, BRAND_PNG)
  console.log(`wrote ${BRAND_PNG} (${logoPng.length} bytes)`)

  const embedOut = path.join(ROOT, 'lib/labels/elementLabsEmbeddedAssets.ts')
  writeFileSync(
    embedOut,
    [
      '// AUTO-GENERATED by scripts/build-element-labs-template.ts — do not edit by hand.',
      '// Base64 Element Labs label template PNG for Vercel (public/ is not in serverless bundles).',
      '',
      `export const ELEMENT_LABS_TEMPLATE_PNG_B64 = '${Buffer.from(labelPng).toString('base64')}'`,
      '',
    ].join('\n')
  )
  console.log(`wrote ${embedOut}`)
}

main()
